language: php
php:
  - '7.0'
deploy:
- provider: s3
  region: eu-west-1
  access_key_id: AKIAJ7WJ4TT32DNLV5GQ
  secret_access_key: &1
    secure: 0ZjqG7AQTQfV7h1sWeelD++XcVbD0K8zXk6W8aeGVLCwoctHSJOUS+wnxQN0OVC6QEXFkJFWF+C9i+d8BRm3MRQx4kdtsY3x/giLtfNVaM3ax0vNOnxSsYmAIOiaE3inBU47rjN659x5eL3Ilwdi6UdMoAZAxZrRuN1u1grdFWw3EO7Zgnz+X45XRAcw9KVFRFW60kboCkLXd7J1HqSACZEwwL5hat6Jr0dufK9wnXz/+cx9ijOTMaGUhEkCg1Zdn9wK+y3UB/9VxqQDOhWcAg+r48AWd39fLoLA2epVSXBMhtXlCqRg95rgRUMHlbNCuvskpvIgvCxA3n7EkstNB3RHUyClU9d7L3QKRv3gZw4uVuiHTmmVuAOyqmj/X19j393Twg68OGeWBZG0e4yOE7hHgVA1KUakXvaOpDX6S30qF3Z4n4vZNQoIHxvYDHdTPhvp3oTqu5qeBHgtI0jtdsG3TP2yEVpBY6ohvV0AWxOqN/XvJMBb5od6cIoht9AV+stzKeMkSPZyietQLmlfdZ4G+pgBbqdDE4Tw2AnE2w+no6Mm4cv+EW7pVezxu0fEy79GoWW1iBYmnv+/k7ffkELyB8CRVKttneOCR/j/6uXt1V8RO48x3jujnboui/pucRbRvfT2gf655yGoFVp8HvSP3KnK8fATnkbhzkjysIM=
  local_dir: dpl_cd_upload
  skip_cleanup: false
  on: &2
    repo: demeilliez/aws
  bucket: cedric-test-compartiment
  upload_dir: latest
- provider: codedeploy
  region: eu-west-1
  access_key_id: AKIAJ7WJ4TT32DNLV5GQ
  secret_access_key: *1
  bucket: cedric-test-compartiment
  key: latest/MyApp.zip
  bundle_type: zip
  application: cedric-test-integration
  deployment_group: grp-cedric-test-integration
  on: *2
before_deploy:
  - zip MyApp -r *
  - mkdir -p dpl_cd_upload
  - mv MyApp.zip dpl_cd_upload/MyApp.zip
script:
- phpunit --coverage-clover --bootstrap stacktest.php