language: php
php:
  - '7.0'
deploy:
- provider: s3
  region: eu-west-1
  access_key_id: AKIAJ7WJ4TT32DNLV5GQ
  secret_access_key: &1
    secure: dBucc77z9RHlSCMRVw5SCY8cHZvXDXZ/6EL4na0XeHmfMGe5/X+8CtfsEAkeJCyrAIK+YmtpqQg3Qa8j4Jb7oDIRL4iUg3G/St8gRidhmXZKc9ZgF+nWW7AhWrj8wMU5Xy0NwgGjUocaGEMC5pwG23nsSwHS0oRl54ZCI4ak6f0T8nXAPZk46EzHloay9emDcHYBqtKIcQdR8APEpKeZkiWpGOaCDIZU519bkS1SfDmESYHGlBkjwTznPdzyx/eVXbD4WfsUeM4Z/KvznW+ROU6eP71CprnFRdsogz/V2fKSHAOZDHBbnWARTiu1kKc13XWYDS4VLyhiWH1IiwrmJygQfiok2l3t+xv41syC8xTbUNZc1eSFQxZZ7TI4z9vqbRoenZ4CiTKM+P12RpHqAqLJGGrMFHgfJwspIRKtLCJSrrE77RymHOwAwWj/vfW8CCKV4rIdWIn1IhocDauGsEAKJoR8Yawb4Hu8JhPJ8St7FUK/CqcFdyEL9e5CQvjAkZ6iENto1hDYgo4szOwQV9pNY+Vxi9Vb2mXEhJAHj1dgvcmgM8rvevgu7f5UJDhpJ8Ka5PqJvrcgjtI/niusDK2It3lfRpBDDjs0kV24u+ipL3RAEHMTRMJtNUE8pOheFBVNdIUtrYzMTcqKYDE8P58HJ6kCJOHt8RETggPV0Bo=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: demeilliez/aws2
  bucket: cedric-test-compartiment
  upload_dir: latest
- provider: codedeploy
  region: eu-west-1
  access_key_id: AKIAJ7WJ4TT32DNLV5GQ
  secret_access_key: *1
  bucket: cedric-test-compartiment
  key: latest/MyApp.zip
  bundle_type: zip
  application: cedric-test-integration
  deployment_group: grp-cedric-test-integration
  on: *2
before_deploy:
  - zip MyApp -r *
  - mkdir -p dpl_cd_upload
  - mv MyApp.zip dpl_cd_upload/MyApp.zip
script:
- phpunit --coverage-clover --bootstrap stacktest.php