language: php
php:
  - '7.0'
deploy:
- provider: codedeploy
  region: eu-west-1
  access_key_id: AKIAJ7WJ4TT32DNLV5GQ
  secret_access_key: *1
  bucket: cedric-test-compartiment
  key: latest/MyApp.zip
  bundle_type: zip
  application: cedric-test-integration
  deployment_group: grp-cedric-test-integration
  on: *2
before_deploy:
  - zip MyApp -r *
  - mkdir -p dpl_cd_upload
  - mv MyApp.zip dpl_cd_upload/MyApp.zip
script:
- phpunit --coverage-clover --bootstrap stacktest.php